---
- name: Install a package
  hosts: all
  become: true
  become_user: root
  become_method: sudo

  tasks:
    - name: Update repository Index and installing apache2 and php packages for Unbuntu
      apt: 
        package:
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"


    - name: installing apache2 and php packages for Centos
      dnf:
        name:
          - httpd
          - php
        state: latest
        update_cache: yes
      when: ansible_distribution == "Centos"
